Correctly mark groovy and java source folders
qbicsoftware/qube-cli pull request #237
Opened 2020-11-27 12:45 UTC by jenniferboedker

Many thanks for contributing to QUBE!

**Description of changes**
The current version of qube is creating portlets where the source folder is not marked. Furthermore, the portlet cannot run error-free because the notation from java (@component annotation) cannot be translated to groovy. This PR updates the POM to recognize both, groovy and java, as source folders and fixes the portlet template such that it produces a template that works from scratch.

**Technical details**
The source folders are specified in the POM. Furthermore, some specifications have been added to the `build-helper-maven-plugin` plugin to enable maven in finding the groovy source folder.

2020-11-27 12:46 UTC, jenniferboedker commented
![](https://github.trello.services/images/mini-trello-icon.png) [Transfer example portlet into qube template generation](https://trello.com/c/nK6fbOkj/14-transfer-example-portlet-into-qube-template-generation)

2020-11-30 14:55 UTC, sven1103 commented on qube/create/templates/portlet/portlet_groovy_osgi/{{ cookiecutter.project_slug }}/pom.xml
> +            <url>https://qbic-repo.qbi.uni-tuebingen.de/repository/maven-releases</url>
qbic

2020-11-30 14:56 UTC, sven1103 commented on qube/create/templates/portlet/portlet_groovy_osgi/{{ cookiecutter.project_slug }}/pom.xml
> +
great! 🎉

2020-11-30 14:57 UTC, jenniferboedker commented on qube/create/templates/portlet/portlet_groovy_osgi/{{ cookiecutter.project_slug }}/pom.xml
> +            <url>https://qbic-repo.qbi.uni-tuebingen.de/repository/maven-releases</url>
🙈

2020-11-30 14:57 UTC, jenniferboedker commented on qube/create/templates/portlet/portlet_groovy_osgi/{{ cookiecutter.project_slug }}/pom.xml
> +            <url>https://qbic-repo.qbi.uni-tuebingen.de/repository/maven-releases</url>
can you make a suggestion?

2020-11-30 14:58 UTC, sven1103 requested changes
Only some minor request, otherwise really good!

2020-11-30 14:59 UTC, sven1103 commented on qube/create/templates/portlet/portlet_groovy_osgi/{{ cookiecutter.project_slug }}/pom.xml
> +            <url>https://qbic-repo.qbi.uni-tuebingen.de/repository/maven-releases</url>
```suggestion
            <url>https://qbic-repo.qbic.uni-tuebingen.de/repository/maven-releases</url>
```

2020-12-01 08:11 UTC, sven1103 approved these changes
LGTM!

2020-12-01 08:20 UTC, merged